id: extract-all
namespace: acme.weather

concurrency:
  behavior: QUEUE
  limit: 5

labels:
  - key: kind
    value: control

tasks:

  - id: run_extract
    type: io.kestra.plugin.core.flow.ForEach
    values: '["Paris", "Berlin"]'
    tasks:

      - id: subflow
        type: io.kestra.plugin.core.flow.Subflow
        namespace: acme.weather
        flowId: extract
        inputs:
          time: '{{ trigger.date ?? now() | date("yyyy-MM-dd") }}'
          city: "{{ taskrun.value }}"

triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "@daily"
    allowConcurrent: true