#!/bin/bash

# Script to generate terraform/.auto.tfvars from .env file
# This allows both Docker Compose and Terraform to use the same secret values

set -e

# Check if .env file exists
if [ ! -f ".env" ]; then
    echo "Error: .env file not found!"
    echo "Please copy env.example to .env and fill in your values:"
    echo "  cp env.example .env"
    echo "  # Edit .env with your actual values"
    exit 1
fi

# Source the .env file
set -a
source .env
set +a

# Function to convert UPPER_CASE to snake_case
to_snake_case() {
    echo "$1" | tr '[:upper:]' '[:lower:]'
}

# Generate .auto.tfvars for Terraform
# Read .env file and convert each variable
{
    echo "# Auto-generated from .env file"
    echo "# DO NOT EDIT THIS FILE MANUALLY - Run generate-tf-vars.sh to regenerate"
    echo ""
    
    # Read .env file line by line
    while IFS= read -r line || [ -n "$line" ]; do
        # Skip empty lines and comments
        if [[ -z "$line" ]] || [[ "$line" =~ ^[[:space:]]*# ]]; then
            continue
        fi
        
        # Check if line contains an assignment
        if [[ "$line" =~ ^([^=]+)=(.*)$ ]]; then
            env_var="${BASH_REMATCH[1]}"
            env_value="${BASH_REMATCH[2]}"
            
            # Remove leading/trailing whitespace
            env_var=$(echo "$env_var" | xargs)
            env_value=$(echo "$env_value" | xargs)
            
            # Skip if empty
            if [[ -z "$env_var" ]]; then
                continue
            fi
            
            # Convert to snake_case
            tf_var=$(to_snake_case "$env_var")
            
            # Get the actual value from the environment (handles quotes and special chars)
            actual_value="${!env_var}"
            
            # Write to tfvars file if variable is set
            if [[ -n "$actual_value" ]]; then
                echo "${tf_var} = \"${actual_value}\""
            fi
        fi
    done < .env
} > terraform/.auto.tfvars

echo "✅ Generated terraform/.auto.tfvars from .env file"
echo "📝 You can now run 'cd terraform && terraform plan' to use these variables"
